### ISSUE TITLE
Gorion's robe is not a real Knave's Robe

### ISSUE THREAD

**Issue by burner1024** [Spellhold-Studios/BGT-WeiDU#83]
Mage starter pack, Gorion's leftover robe is `clck18`, which appears to be `clck12`, but has no corresponding effects. Probably was used for cosmetic purposes in BG1?
I suggest to replace it with `clck12` in this instance, and others too. (From my search, `gorion.cre`, `gorion3.cre` and `daerragh.cre`)

**Comment by skellytz** [comment]
I'll look into it. Thanks, as always!

**Comment by burner1024** [comment]
Sorry, after double checking I found out that it's actually undroppable in original.
The drop is caused by Nightfarer's Item Patcher.
I guess it couldn't hurt to drop a proper robe. But there's no bug per se, so it's up to you.
